config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'toppages#index'
  
  get 'login',  to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  get 'signup', to:'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :joined_teams
    end
  end
  resources :teams, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :members
    end
  end
  resources :tasks, only: [:show, :create, :edit, :update,]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  validates :team_name, presence: true, length: { maximum:50 }
  
  has_many :tasks
  has_many :relationships
  has_many :members, through: :relationships, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :relationships
  has_many :joined_teams, through: :relationships, source: :team
  
  def join(team)
    self.relationships.create(team_id: team.id)
  end
  
  def unjoin(team)
    relationship = self.relationships.find_by(team_id: team.id)
    relationship.destroy if relationship
  end
  
  def joined_team?(team)
    self.joined_teams.include?(team)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    team = Team.find(params[:team_id])
    current_user.join(team)
    flash[:success]='チームに参加しました'
    redirect_to team
  end

  def destroy
    team = Team.find(params[:team_id])
    current_user.unjoin(team)
    flash[:success]='チームから脱退しました'
    redirect_to teams_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success]= 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:danger]= 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id]= nil
    flash[:success]= 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id]= @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    
    if @task.save
      flash[:success]= 'タスクは正常に追加されました'
      redirect_to @task
    else
      flash.now[:danger]= 'タスクを追加できませんでした'
      render 'teams/show'
    end
      
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:success]= 'タスクは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger]= 'タスクを更新できませんでした'
      render :edit
    end
    
    
  end
  
  private
  
  def task_params
    params.require(:task).permit(:title, :content, :progress, :due_date, :team_id)
  end  
  
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @team = Team.new
    @teams = Team.order(id: :desc).page(params[:page])
  end

  def show
    @team = Team.find(params[:id])
    @tasks = @team.tasks.order(id: :desc).page(params[:page])
    @task = Task.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:success]='チームを作成しました'
      redirect_to @team
    else
      flash.now[:danger]='チームの作成に失敗しました'
      render :index
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    
    if @team.update(team_params)
      flash[:success]= 'Teamは正常に更新されました'
      redirect_to @team
    else
      flash.now[:danger]= 'Teamは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    
    flash[:success]= 'Teamは削除しました'
    redirect_to teams_url
  end
  
  def members
    @team = Team.find(params[:id])
    @members = @team.members.page(params[:page])
    @task = Task.new
  end  
  
  private
  
  def team_params
    params.require(:team).permit(:team_name)
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @teams = current_user.joined_teams
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
  end

  def show
    @user = User.find(params[:id])
    @joined_teams = @user.joined_teams.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_param)
    
    if @user.save
      flash[:success]= 'ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger]='ユーザの登録に失敗しました'
      render :new
    end
  end
  
  private
  
  def user_param
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user,option = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class='mb-4'>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Teamtasks</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="NavbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Teams',teams_path ,class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>  
          <li class="nav-item"><%= link_to 'Sign up', signup_path , class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset= 'utf-8'>
    <meta name= "viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Teamtasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/_join_botton.html.erb
<% unless current_user.joined_team?(team) %>
  <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
    <%= hidden_field_tag :team_id, team.id %>
    <%= f.submit 'Join team', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>
  

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/edit.html.erb
<h2>タスク編集</h2>


    <%= form_with(model: @task, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :title, 'Task' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content, 'Detail' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :progress, 'Progress' %>
        <%= f.text_field :progress, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :due_date, 'Due date' %>
        <%= f.date_field :due_date, class: 'form-control' %>
      </div>
      
      <%= f.submit 'edit', class: 'btn btn-warning btn-block' %>
    <% end %>
    
<p><%= link_to '戻る', @task %></p>
    

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/show.html.erb
<h2>タスク詳細</h2>
<div>
  <p><%= @task.title %> updated at <%= @task.updated_at %></p>
</div>
<div>
  <p><%= @task.content %></p>
</div>
<div>
  <p><%= @task.progress %></p>
</div>
<div>
  <p><%= @task.due_date %></p>
</div>
<div>
  <%= link_to 'edit', edit_task_path, class: 'btn btn-warning btn-sm' %>
<div/>
<p><%= link_to '一覧に戻る', team_path(@task.team) %></p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ：<%= current_user.name %></p>
  <div class="row">
    <aside class="col-sm-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><%= current_user.name %></h3>
        </div>
        <div class="card-body">
          <img class="rounded img-fluid" src="<%= gravatar_url(current_user, { size: 500 }) %>" alt="">
        </div>
      </div>
    </aside>
    <div class="col-sm-8 pl-5">
      <ul class="list-unstyled">
        <% @teams.each do |team| %>
        <% team.tasks.each do |task| %>
          <li class="mb-3">
            <div>
              <span class="mr-5"><%= task.team.team_name %></span><span>Due date：<%= task.due_date %></span>
            </div>
            <div>
              <%= link_to task.title, task_path(task) %> <span class="text-muted">updated at <%= task.updated_at %></span>
            </div>
            <div>
              <p><%= task.progress %></p>
            </div>
          </li>
        <% end %>
        <% end %>
      </ul> 
    </div>
  </div>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Teamtasks</h1>
      <%= link_to 'sign up now!', signup_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
        
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>  
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8 pl-5">
    <h4>My Teams</h4>
    <%= render 'teams/teams', teams: @joined_teams %> 
  </div>
</div>